# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jerome Nelson
email: "me@jerome-nelson.dev"
description: >- # this means to ignore newlines until "baseurl:"
  Front-End Developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "jerome-nelson.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "jerome-nelson"


# Build settings
markdown: kramdown
theme: minima
include: ["_data"]
plugins:
  - jekyll-feed
  - jekyll-contentful-data-import
  - rich_text_renderer
contentful:
  spaces:
    - blog:
        cda_query:
          include: 2
          limit: 10
        content_types:
          blogPost: posts
        space: uwk4nvt2pnyc
        access_token: 89147a4fb9d97336f083ea2800a7ad5f6b42209c6848de177be0fc17c59a5e50
        destination: "/"
        individual_entry_files: true